Basic Controls Testing: '--format html --tags @basic --overwrite'
Advanced Controls Testing: '--format html --tags "@basic or @advanced"'
Recording: '--format html --video'
Presentation: '--format html --tags "not @todo"'
